name: Evaluator
main: dktapps\Evaluator\Main
version: 0.1.0
api: [3.0.0]
load: POSTWORLD
author: dktapps
description: Evil plugin
website: https://github.com/dktapps/Evaluator
commands:
 eval:
  description: "runs arbitrary PHP code"
  usage: "/eval <code...>"
  permission: "false"
